#!/bin/zsh
# Script to sync Claude Code user config to git repo
# Copies: skills, commands, agents, settings, and CLAUDE.md

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Source directories
CLAUDE_DIR="$HOME/.claude"
CLAUDE_JSON="$HOME/.claude.json"
SOURCE_DIRS=(
    "skills"
    "commands"
    "agents"
)
SOURCE_FILES=(
    "CLAUDE.md"
)

# Files to copy (settings.json excluded for privacy)
SKIP_FILES=(
    "settings.json"
    "settings.local.json"
)

# Current working directory (destination)
DEST_DIR="$(pwd)"

echo -e "${GREEN}=== Claude Config Sync Script ===${NC}"
echo "Destination: $DEST_DIR"
echo ""

# Function to mask API keys in JSON
mask_api_keys() {
    local input_file="$1"
    local output_file="$2"

    # Mask common API key patterns using Perl for better regex support
    perl -pe '
        # Mask ANTHROPIC_AUTH_TOKEN value (handles dots and special chars)
        s/"ANTHROPIC_AUTH_TOKEN":\s*"[^"]*"/"ANTHROPIC_AUTH_TOKEN": "***MASKED***"/g;
        # Mask any field containing "key", "token", "secret", "password" (case insensitive)
        s/"([^"]*[Kk]ey[^"]*|[^"]*[Tt]oken[^"]*|[^"]*[Ss]ecret[^"]*|[^"]*[Pp]assword[^"]*)":\s*"[^"]*"/"\1": "***MASKED***"/g;
    ' "$input_file" > "$output_file"
}

# Step 1: Copy directories
echo -e "${YELLOW}Copying directories...${NC}"
for dir in "${SOURCE_DIRS[@]}"; do
    src="$CLAUDE_DIR/$dir"
    if [ -d "$src" ]; then
        echo "  Copying $dir/"
        cp -r "$src" "$DEST_DIR/"
    else
        echo -e "  ${RED}Warning: $src not found, skipping${NC}"
    fi
done

# Step 2: Copy individual files
echo ""
echo -e "${YELLOW}Copying files...${NC}"
for file in "${SOURCE_FILES[@]}"; do
    src="$CLAUDE_DIR/$file"
    if [ -f "$src" ]; then
        echo "  Copying $file"
        cp "$src" "$DEST_DIR/"
    else
        echo -e "  ${RED}Warning: $src not found, skipping${NC}"
    fi
done

# Step 3: Extract MCP servers from ~/.claude.json
echo ""
echo -e "${YELLOW}Extracting MCP servers config...${NC}"
MCP_DEST="$DEST_DIR/mcp-servers.json"

if [ -f "$CLAUDE_JSON" ]; then
    # Extract mcpServers section and mask API keys
    if command -v jq &> /dev/null; then
        echo "  Extracting mcpServers from ~/.claude.json"
        jq '.mcpServers' "$CLAUDE_JSON" 2>/dev/null | \
        perl -pe '
            # Mask API keys (matches KEY, TOKEN, SECRET, API anywhere in the key name)
            s/"([^"]*(?:KEY|TOKEN|SECRET|API)[^"]*)":\s*"[^"]*"/"\1": "***MASKED***"/gi;
            # Mask Authorization headers (Bearer tokens)
            s/"Authorization":\s*"Bearer\s+[^"]*"/"Authorization": "Bearer ***MASKED***"/gi;
            # Mask file paths (matches PATH, FILE, DIR anywhere in the key name)
            s/"([^"]*(?:PATH|FILE|DIR)[^"]*)":\s*"[^"]*"/"\1": "***MASKED PATH***"/gi;
        ' > "$MCP_DEST"
        echo "  Created mcp-servers.json (with masked API keys)"
    else
        echo -e "  ${YELLOW}Warning: jq not found, skipping MCP export${NC}"
    fi
else
    echo -e "  ${RED}Warning: $CLAUDE_JSON not found${NC}"
fi

# Step 4: Create .gitignore
echo ""
echo -e "${YELLOW}Creating .gitignore...${NC}"
cat > "$DEST_DIR/.gitignore" << 'EOF'
# History and debug files
history.jsonl
debug/
shell-snapshots/
todos/
file-history/
session-env/
telemetry/
projects/
plans/
cache/
downloads/
paste-cache/
statsig/
output-styles/
ide/
temp/
*.log

# OS files
.DS_Store
Thumbs.db

# Editor files
.vscode/
.idea/
*.swp
*.swo
*~

# Plugin cache (we only want custom configs)
plugins/cache/
plugins/marketplaces/

# Environment files
envs/.local/
EOF

echo "  Created .gitignore"

# Step 5: Create README
echo ""
echo -e "${YELLOW}Creating README.md...${NC}"
cat > "$DEST_DIR/README.md" << 'EOF'
# Claude Code Config Sync

This repository contains my personal Claude Code configuration files, synced from `~/.claude/`.

## Contents

- **`CLAUDE.md`** - Global instructions for Claude
- **`skills/`** - Custom skills
- **`commands/`** - Slash commands
- **`agents/`** - Custom subagents
- **`settings.json`** - Claude Code settings (API keys masked)

## API Keys

All sensitive API keys and tokens in `settings.json` are masked with `***MASKED***`.
You'll need to update these with your own values.

## Syncing

Run the sync script to update this repo from your local config:

```bash
./sync-claude-config.sh
```

---

Generated by Claude Code Config Sync Script
EOF

echo "  Created README.md"

# Step 6: Git operations
echo ""
echo -e "${YELLOW}Setting up git repository...${NC}"

# Check if git is initialized
if [ ! -d ".git" ]; then
    echo "  Initializing git repo..."
    git init

    # Check if gh CLI is available for repo creation
    if command -v gh &> /dev/null; then
        echo "  Creating GitHub repo using gh CLI..."
        echo -n "Enter repo name (default: claude-config): "
        read repo_name
        repo_name=${repo_name:-claude-config}

        echo -n "Enter GitHub username (or press for default): "
        read github_user
        if [ -z "$github_user" ]; then
            github_user=$(git config github.user 2>/dev/null || echo "")
        fi

        if [ -n "$github_user" ]; then
            gh repo create "$github_user/$repo_name" --public --source=. --remote=origin --push
        else
            gh repo create "$repo_name" --public --source=. --remote=origin --push
        fi
    else
        echo "  gh CLI not found. Please create repo manually on GitHub."
        echo "  Then run:"
        echo "    git remote add origin <your-repo-url>"
        echo "    git push -u origin main"
    fi
else
    echo "  Git repo already initialized"
fi

# Add all files
echo ""
echo "  Adding files to git..."
git add .

# Commit
echo "  Creating commit..."
git commit -m "Sync Claude Code config

- Skills: $(ls -1 skills/ 2>/dev/null | wc -l | tr -d ' ') items
- Commands: $(ls -1 commands/ 2>/dev/null | wc -l | tr -d ' ') items
- Agents: $(ls -1 agents/ 2>/dev/null | wc -l | tr -d ' ') items

Generated by sync-claude-config.sh"

echo ""
echo -e "${GREEN}=== Sync Complete! ===${NC}"
echo ""
echo "Next steps:"
echo "  1. Review the copied files in: $DEST_DIR"
echo "  2. Check that API keys are properly masked in settings.json"
echo "  3. Push to GitHub if not already done:"
echo "     git push -u origin main"
echo ""
